version: '3'
services:
  leafy-postgres:
#    build: ./leafy-postgresql
    image: dongwook0108/leafy-postgres:54a963b7a4e1fabae155bf026e74dc14b0be6ea5
    volumes:
      - mydata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: always

  leafy-backend:
#    build: ./leafy-backend
    image: dongwook0108/leafy-backend:cc2f6832d6a2fb103eecfe75e4abaf2a10dd2d2f
    environment:
      - DB_URL=leafy-postgres
    depends_on:
      - leafy-postgres
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure
      
  leafy-front:
#    build: ./leafy-frontend
    image: dongwook0108/leafy-frontend:ccf4831347c2c2bba2d300b4270970a45f8a1e8b
    environment:
      - BACKEND_HOST=leafy-backend
    ports:
      - 80:80
    depends_on:
      - leafy-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: on-failure

volumes:
  mydata: